# Generated by Django 2.2.7 on 2019-11-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_auto_20191106_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
