# Generated by Django 2.2.7 on 2019-11-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_auto_20191107_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='image',
            field=models.ImageField(upload_to='dataSets', verbose_name='Imagen'),
        ),
    ]
