# Generated by Django 2.2.7 on 2019-11-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_auto_20191107_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='classifier',
            field=models.CharField(choices=[('LRC', 'Logistic Regression'), ('SVM', 'Maquina de Sporte Vectorial'), ('RIE', 'Riemmanian Classifier')], default='', max_length=10, verbose_name='Selección de Información'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dimension',
            field=models.CharField(choices=[('NON', 'Ninguno'), ('PCA', 'PCA'), ('EAP', 'EAP'), ('EEP', 'EEP')], default='', max_length=10, verbose_name='Reducción Dimensional'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='features',
            field=models.CharField(choices=[('CNN', 'Red Convolucional'), ('INC', 'Red Inception'), ('SCA', 'Autoencoder Convolucional Apilado'), ('BCA', 'Autoencoder Convolucional Ramificado')], default='', max_length=10, verbose_name='Extracción de Caracteristicas'),
        ),
    ]
