# Generated by Django 2.2.7 on 2019-11-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_auto_20191108_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='classifier',
            field=models.CharField(choices=[('LRC', 'Logistic Regression'), ('SVM', 'Maquina de Sporte Vectorial'), ('RIE', 'Riemannian Classifier')], default='', max_length=10, verbose_name='Selección de Información'),
        ),
    ]
