# Generated by Django 2.2.7 on 2019-11-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0007_auto_20191108_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='classifier',
            field=models.CharField(choices=[('LRC', 'Logistic Regression'), ('SVM', 'Maquina de Sporte Vectorial'), ('RIE', 'Riemannian Classifier')], default='', max_length=10, verbose_name='Metodo de Selección de Información'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dimension',
            field=models.CharField(choices=[('NON', 'Ninguno'), ('PCA', 'PCA'), ('EAP', 'EAP'), ('EEP', 'EEP')], default='', max_length=10, verbose_name='Metodo de Reducción Dimensional'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='features',
            field=models.CharField(choices=[('CNN', 'Red Convolucional'), ('INC', 'Red Inception'), ('SCA', 'Autoencoder Convolucional Apilado'), ('BCA', 'Autoencoder Convolucional Ramificado')], default='', max_length=10, verbose_name='Metodo de Extracción de Caracteristicas'),
        ),
    ]
