# Generated by Django 2.2.7 on 2020-01-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0009_auto_20191113_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='description_US',
            field=models.TextField(default='', verbose_name='Descripción_US'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(default='', verbose_name='Descripción'),
        ),
    ]
