# Generated by Django 2.2.7 on 2020-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0010_auto_20200116_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='classifier',
            field=models.CharField(choices=[('LRC', 'Logistic Regression'), ('SVM', 'Support Vector Machine'), ('RIE', 'Riemannian Classifier')], default='', max_length=10, verbose_name='Metodo de Selección de Información'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dimension',
            field=models.CharField(choices=[('NON', 'None'), ('PCA', 'Principal Component Analysis'), ('EAP', 'Attibute Profiles'), ('EEP', 'Extintion Profiles')], default='', max_length=10, verbose_name='Metodo de Reducción Dimensional'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='features',
            field=models.CharField(choices=[('CNN', 'Convolutional Neural Network'), ('INC', 'Inception Network'), ('SCA', 'Stacked Autoencoder CNN'), ('BCA', 'Branched Autoencoder CNN')], default='', max_length=10, verbose_name='Metodo de Extracción de Caracteristicas'),
        ),
    ]
